# Generated by Django 4.1 on 2022-08-14 21:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('shop', '0004_product_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimage',
            options={'verbose_name': 'Изоброжение', 'verbose_name_plural': 'Изоброжении'},
        ),
        migrations.AddField(
            model_name='productimage',
            name='style_active',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
